version: 2
builds:
  - id: cowsay
    dir: cmd
    main: ./cowsay/main.go
    binary: cowsay
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X main.version={{.Version}}
    goos:
      - "linux"
      - "darwin"
      - "windows"
    goarch:
      - "386"
      - "amd64"
      - "arm"
      - "arm64"
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: linux
        goarch: arm
        goarm: "7"
      - goos: windows
        goarch: arm
        goarm: "7"
  - id: cowthink
    dir: cmd
    main: ./cowthink/main.go
    binary: cowthink
    env:
      - CGO_ENABLED=0
    ldflags: -s -w -X main.version={{.Version}}
    goos:
      - "linux"
      - "darwin"
      - "windows"
    goarch:
      - "386"
      - "amd64"
      - "arm"
      - "arm64"
    goarm:
      - "6"
      - "7"
    ignore:
      - goos: darwin
        goarch: "386"
      - goos: linux
        goarch: arm
        goarm: "7"
      - goos: windows
        goarch: arm
        goarm: "7"

archives:
  - ids:
      - cowsay
      - cowthink
    name_template: >-
      {{- .ProjectName }}_{{ .Version }}_
      {{- if eq .Os "darwin" }}macOS
      {{- else if eq .Os "linux" }}Linux
      {{- else if eq .Os "windows" }}Windows
      {{- else }}{{ .Os }}{{ end }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        formats: ['zip']
    files:
      - LICENSE
      - doc/cowsay.1

brews:
  - name: neo-cowsay
    repository:
      owner: Code-Hex
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: https://github.com/Code-Hex/Neo-cowsay
    description: "Fast, funny, everyone wanted? new cowsay!!"
    directory: Formula
    install: |
      bin.install "cowsay"
      bin.install "cowthink"
      man1.install Dir["doc/cowsay.1"]

nfpms:
  - license: Artistic License 2.0
    maintainer: Kei Kamikawa <x00.x7f.x86@gmail.com>
    homepage: https://github.com/Code-Hex/Neo-cowsay
    bindir: /usr/local/bin
    description: "Fast, funny, everyone wanted? new cowsay!!"
    formats:
      - apk
      - deb
      - rpm
    contents:
      - src: "doc/cowsay.1"
        dst: "/usr/share/man/man1/cowsay.1"

checksum:
  name_template: 'cowsay_checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch
