on:
  push:
    tags:
      - "v*.*.*"

jobs:
  release:
    name: Release
    runs-on: ubuntu-latest
    steps:
      - name: Setup Go 1.17.2
        uses: actions/setup-go@v2
        with:
          go-version: 1.17.2
      - name: Check out code into the Go module directory
        uses: actions/checkout@v3
      - name: Run GoReleaser
        if: contains(github.ref, 'tags/v')
        uses: goreleaser/goreleaser-action@v6
        with:
          version: "~> v2"
          args: release --clean
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
